# Helm chart
# You can easily deploy soarflow and OpenSearch in kubernetes with the helm chart.


apiVersion: v2
name: soarflow

type: application

version: 0.1.0


dependencies:
  - name: opensearch-with-dashboard
    version: 0.1.0
    repository: "file://opensearch"

