apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    bitahoy.id: {{ .Release.Name }}-app
  name: {{ .Release.Name }}-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      bitahoy.id: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        bitahoy.id: {{ .Release.Name }}-app
    spec:
      containers:
      - env:
        - name: MODULE_NAME
          value: app
        image: bitahoy/soarflow
        imagePullPolicy: "Always"
        name: {{ .Release.Name }}-app
        ports:
        - containerPort: 80
        resources: {}
        #securityContext: 
          #readOnlyRootFilesystem: true
        volumeMounts: []
        resources:
          requests:
            memory: "64Mi"
            cpu: "16m"
          limits:
            memory: "1Gi"
            cpu: "512m"
        readinessProbe:
          httpGet:
            path: /?readinessprobe=true
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
      restartPolicy: Always
      serviceAccountName: ""
      volumes: []
      imagePullSecrets:
        - name: myregistrykey
status: {}