apiVersion: v1
kind: Service
metadata:
  labels:
    bitahoy.id: {{ .Release.Name }}-app
  name: {{ .Release.Name }}-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    bitahoy.id: {{ .Release.Name }}-app
status:
  loadBalancer: {}